### ISSUE TITLE
alter the builder script to pull data directly from a database instead of building from JSON

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/automatic-archives#3]
Currently: we use a file in the repository to do this.

Interim: we could reference the regularly updated file in [this mirror repository](https://github.com/Police-Data-Accessibility-Project/data-sources-mirror) if we for some reason don't want to use our API.

Ideally: we should reference the Data Sources API endpoint from this issue: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/1

**Comment by kalenluciano** [comment]
See issue #5
