### ISSUE TITLE
alter workflow to automatically add URLs to the active cache list when new entries appear in the database

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/automatic-archives#4]
Requires closing #3

**Comment by mbodeantor** [comment]
@josh-chamberlain how frequently should new urls be cached as a default? Should all urls be added that aren't currently being cached?

**Comment by josh-chamberlain** [comment]
@mbodeantor default of `weekly` seems right based on my experience, or `monthly` if we want to be more conservative. some sources have a lower retention rate than that, but it's an OK default.

Yes, unless there's some reason we should specifically _avoid_ cacheing them.

**Comment by mbodeantor** [comment]
After going through the code in depth, I'm pretty sure we're already caching everything in the data_sources table that has a source_url. @kalenluciano do you agree?

Since it seems like that is the case, I'm going to just fill in any blank update_frequency fields with "weekly".

**Comment by josh-chamberlain** [comment]
@mbodeantor you'll notice there's no standardization to that field, because we didn't know what we were gonna get and some of the update_frequency selections would be, like, "every time there's an officer-involved use of force". LMK if you think we could make a set of options which would cover it, maybe for those we could use `incident-based` or `event-driven`.

**Comment by mbodeantor** [comment]
@josh-chamberlain Yeah I think some standardization would be a great idea. Obviously there is some variation in capitalization but would love your thoughts on the rest of those. Would be great to standardize around one label for each number of days or yeah "incident-based"

 ```update_frequency_mapping = {
        "As new shootings occur": 30,
        "quarterly": 91,
        "Quarterly": 45,
        "<5 Minutes": 1,
        "Monthly": 30,
        "annually": 365,
        "daily": 1,
        "Nightly": 1,
        "BiAnnually": 182,
        "About weekly at least": 7,
        "<2 Weeks": 14,
        "Hourly": 1,
        "Daily": 1,
        "At least once per week": 7,
        "semi-annually": 365,
        "Weekly": 7,
        "weekly or more often": 7,
        "Annually": 365,
        "weekly": 7,
        "Irregularly every few months upon complaint or request.": 121,
        "monthly": 30,
        "Live": 1
    }```

**Comment by josh-chamberlain** [comment]
`retention_schedule` is pretty useful here too, similarly unstructured. Working on it

**Comment by josh-chamberlain** [comment]
OK @mbodeantor , `update_frequency` and `retention_schedule` are both selects. I tightened up the options updated the docs. We could use both of these to sort of infer an `archive_schedule` so maybe we should just have users/the data source ID pipeline populate that field directly and ditch these two. 

For incident-based, we could use something like [klaxon](https://github.com/themarshallproject/klaxon) to monitor.

**Comment by josh-chamberlain** [comment]
![Screen Shot 2023-10-03 at 5 36 33 PM](https://github.com/Police-Data-Accessibility-Project/automatic-archives/assets/30379833/12189732-f456-4566-88b8-c93fafc170e2)

![Screen Shot 2023-10-03 at 5 36 16 PM](https://github.com/Police-Data-Accessibility-Project/automatic-archives/assets/30379833/0364f46f-6860-468c-a9f1-cc8bcedf4b91)

**Comment by mbodeantor** [comment]
Cool, I'll update the update_frequency column to reflect the new dropdown

**Comment by mbodeantor** [comment]
Oh you already did it lol

**Comment by mbodeantor** [comment]
@josh-chamberlain So currently this script is set to run monthly. I think it makes sense to run it hourly and then just ignore the majority until it actually needs to be updated. Looks like we only have one source labelled < Hourly right now.

**Comment by mbodeantor** [comment]
@josh-chamberlain Only seeing a couple incident-based ones rn. Maybe we just have these archive weekly for now?

**Comment by josh-chamberlain** [comment]
totally fine for now @mbodeantor, but let's keep klaxon in mind for the future (I have it saved [here](https://www.notion.so/pdap/Software-to-keep-in-mind-0b24978d83ae4b79a893f259c720cbdd?pvs=4))
